# Generated by Django 4.0.5 on 2022-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_colorvariant_sizevariant_product_color_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
